### ISSUE TITLE
Potential energy function to be used!

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework7G4#10]
Is this the the potential energy function for the Na4Cl4 cluster that we are going to use for it optimization?
![Screenshot from 2023-11-26 22-12-51](https://github.com/ubsuny/23-Homework7G1/assets/143649367/6c7c3440-661c-470c-a453-b43087114c6d)

**Comment by reshnashrestha** [comment]
This is equation 4 on the paper right?
I believe this is the one.
