### ISSUE TITLE
How to Initialize the cluster geometry to an ideal case?

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework7G4#14]

**Comment by poojashresthacode** [comment]
https://github.com/ubsuny/23-Homework7G5/issues/24 
i think this may be the case.

**Comment by reshnashrestha** [comment]
Thank you pooja

**Comment by tirthbha** [comment]
@reshnashrestha BTW, to initialize the cluster geometry means starting the simulation with the ions (Na+ and Cl-, in our case) arranged in a geometric configuration that is close to what we would expect for the minimum energy structure.

**Comment by reshnashrestha** [comment]
Thank you for explaining
