### ISSUE TITLE
Saddle points

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework7G4#2]
What are saddle points?

**Comment by reshnashrestha** [comment]
Oh nice. Have you started your task?

**Comment by poojashresthacode** [comment]
saddle point is the point of inflection. A point of inflection is a point on the graph of a function where the curve changes its curvature or concavity. In other words, at a point of inflection, the second derivative of the function changes sign. The function transitions from being concave upward to concave downward or vice versa.

We will not encounter saddle point in tetramers during optimization. trimers and pentamers are possible to be encountered by this.

**Comment by reshnashrestha** [comment]
Oh thank  you guys
