### ISSUE TITLE
Potential formula Confusion

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework7G4#21]
The ion-ion potential in K.Michaelian paper is:
![image](https://github.com/ubsuny/23-Homework7G4/assets/143649458/2763ce21-6932-48e6-a6ab-dd13be0ce300)
and the one found in the [Compphys minmax](https://github.com/ubsuny/CompPhys/blob/main/MinMax/nacl.ipynb) is:
![image](https://github.com/ubsuny/23-Homework7G4/assets/143649458/17a67a06-b958-4c8b-87ca-8fa29b15f092)
 
and in the paper, the potential formula is referenced to:
![image](https://github.com/ubsuny/23-Homework7G4/assets/143649458/4e566993-33cc-464c-b43a-d2e42140a19e)
For this homework, which formula should we follow? @laserlab may be you can provide some lead.

**Comment by tirthbha** [comment]
@reshnashrestha I think, we can estimate binding energies by using the relation:
![Screenshot from 2023-11-28 16-51-33](https://github.com/ubsuny/23-Homework7G4/assets/143649367/77bdd884-ac0f-4c47-a4ed-13e8e04e4608)

**Comment by reshnashrestha** [comment]
Okay, I am just confused with which formula to implement on our task.

**Comment by laserlab** [comment]
you can use the one from the notebook

**Comment by reshnashrestha** [comment]
Thank you
