### ISSUE TITLE
Box size!

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework7G4#22]
I have chosen a planar rectangle as one of the 7 configurations, how would we expect to assign the values of a and b (a=length and b=width)? Are we allowed to choose randomly? Because there are no specific values for these terms in the paper?

**I will appreciated your responses.**

**Comment by reshnashrestha** [comment]
@tirthbha 
review my task [rectangular_nacl.ipynb](https://github.com/ubsuny/23-Homework7G4/blob/main/rectangular_nacl.ipynb)
