### ISSUE TITLE
HW explanation,. 

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework7G4#25]
Hello, dear members of the G#4, 
I just want to make sure that I understood correctly about this HW, So all we need to do is to find the positions of the Na and Cl molecules and then make 2 arrays out of them and use the code provided, to find out the potential energy. Once we find the potential energy, we have to run the optimization code and once we run that it will give us the minimum energy. Is that the whole plan?
Thank you.

**Comment by reshnashrestha** [comment]
Seems like it is the all and then we have to discuss our results and lint the code.

**Comment by uarif** [comment]
Okay, yes, the lining of course, thank you

**Comment by reshnashrestha** [comment]
Yeah no worries
