### ISSUE TITLE
Why doesn't the Compphys notebook show any interactive plot? 

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework7G4#27]
<img width="1051" alt="Screenshot 2023-11-30 at 12 03 18 AM" src="https://github.com/ubsuny/23-Homework7G4/assets/66480280/b562a908-93c3-4fa9-a64d-3efb351f8d22">

**Comment by reshnashrestha** [comment]
I was facing the same then after removing the first line on this cell, it worked.
