### ISSUE TITLE
Cubic structure. 

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework7G4#28]
Who took cubic structure in your group? I am facing an issue, **nan"divide by zero encountered in divide"** for potential calculations. I took those 8 indices, and they are all, (a,0,0), (0,0,a), etc. and I considered all indices to be at most "a" apart. Did I take those indices wrong, or am I missing something? 
Thank you.

**Comment by reshnashrestha** [comment]
@uarif I have not encountered such errors following the similar code in compPhys. may be the defined initial positions have some errors.

**Comment by uarif** [comment]
Okay, I will have a look at it thank you
