### ISSUE TITLE
Showing interactive plot: Solved

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework7G4#30]
If you encountered the problem of getting the interactive plot in the Jupyter notebook, you could replace the first line **_%matplotlib notebook_** with _**%matplotlib inline**_ as shown in the figure.
<img width="994" alt="Screenshot 2023-11-30 at 8 02 05 AM" src="https://github.com/ubsuny/23-Homework7G3/assets/66480280/0336d2a0-13e4-4fff-adbd-b9d766768594">

**Comment by reshnashrestha** [comment]
That's nice. However in VS code environment, we don't need that line at all.

**Comment by Pranjal-Srivastava-2023** [comment]
Nice, it works @Mosaddeq107

**Comment by WildJimmy** [comment]
This is a good fix, but can you interact with the plot like this? I don't think I can in colab

**Comment by reshnashrestha** [comment]
Yes it becomes messy.
