### ISSUE TITLE
Plot of first configuration, cube

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework7G4#32]
This the first configuration among 7, with optimized potential -28.69 eV. [G1]
![cubical_configuration](https://github.com/ubsuny/23-Homework7G4/assets/143649367/58b1eeea-8300-49f0-a851-a856108e64fd)

**Your suggestions and corrections will be appreciated**

**Comment by tirthbha** [comment]
Here is the
![Screenshot from 2023-11-30 14-10-05](https://github.com/ubsuny/23-Homework7G4/assets/143649367/50c7065e-5819-4679-a464-39ede704add5)
 image for both initial and optimized positions

**Comment by reshnashrestha** [comment]
![image](https://github.com/ubsuny/23-Homework7G4/assets/143649458/7865bd87-974a-403e-a77b-2070df82d829)
**OPTIMIZED**

**Comment by reshnashrestha** [comment]
![image](https://github.com/ubsuny/23-Homework7G4/assets/143649458/3fe7a398-7048-4c41-95b3-fc3807957442)

**Comment by WildJimmy** [comment]
Yep, looks good to me

**Comment by reshnashrestha** [comment]
Thanks
