### ISSUE TITLE
Anything we could do with binding energy shown in the figure?

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework7G4#33]

**Comment by WildJimmy** [comment]
I am also wondering this for the stranger configurations, I just brute forced it but I feel like there's a more elegant method waiting

**Comment by s4il3sh** [comment]
Do you make use of it? This energy also differentiates the configurations.

**Comment by reshnashrestha** [comment]
I have generated a function and have shown the value of binding energy in the plot.
