### ISSUE TITLE
What is "c" in the formula for potential energy? Is it the distance between Na and Cl ions?

### ISSUE THREAD

**Issue by Pranjal-Srivastava-2023** [ubsuny/23-Homework7G4#41]

**Comment by reshnashrestha** [comment]
a term to stabilize (or "regularize") the computation at small distances with:

$$b = 1.0\;\mathrm{eV}$$

$$c = 0.01\;\mathrm{nm}$$

**Comment by pratibha77118** [comment]
Is it the constant term used for Pauli repulsive energy?
